# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='component.proto',
  package='networkSpiceMessages',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63omponent.proto\x12\x14networkSpiceMessages\"\x8a\x04\n\tComponent\x12\x44\n\rcomponentType\x18\x01 \x01(\x0e\x32-.networkSpiceMessages.Component.ComponentType\x12\r\n\x05nodes\x18\x02 \x03(\t\x12\x0e\n\x06values\x18\x03 \x03(\x02\x12\x11\n\ttolerance\x18\x04 \x03(\x02\x12>\n\nsourceType\x18\x05 \x01(\x0e\x32*.networkSpiceMessages.Component.SourceType\"\x8e\x02\n\rComponentType\x12\x08\n\x04\x63oco\x10\x00\x12\r\n\tCapacitor\x10\x01\x12\x0c\n\x08Inductor\x10\x02\x12\x11\n\rVoltageSource\x10\x03\x12\x11\n\rCurrentSource\x10\x04\x12\"\n\x1eVoltageControlledVoltageSource\x10\x05\x12\"\n\x1e\x43urrentControlledCurrentSource\x10\x06\x12\"\n\x1eVoltageControlledCurrentSource\x10\x07\x12\"\n\x1e\x43urrentControlledVoltageSource\x10\x08\x12\t\n\x05OpAmp\x10\t\x12\x07\n\x03\x42JT\x10\n\x12\x0c\n\x08Resistor\x10\x0b\"4\n\nSourceType\x12\x08\n\x04Sine\x10\x00\x12\n\n\x06Square\x10\x01\x12\x08\n\x04Step\x10\x02\x12\x06\n\x02\x44\x43\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COMPONENT_COMPONENTTYPE = _descriptor.EnumDescriptor(
  name='ComponentType',
  full_name='networkSpiceMessages.Component.ComponentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='coco', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Capacitor', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Inductor', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VoltageSource', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CurrentSource', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VoltageControlledVoltageSource', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CurrentControlledCurrentSource', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VoltageControlledCurrentSource', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CurrentControlledVoltageSource', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OpAmp', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BJT', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Resistor', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=240,
  serialized_end=510,
)
_sym_db.RegisterEnumDescriptor(_COMPONENT_COMPONENTTYPE)

_COMPONENT_SOURCETYPE = _descriptor.EnumDescriptor(
  name='SourceType',
  full_name='networkSpiceMessages.Component.SourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Sine', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Square', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Step', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DC', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=512,
  serialized_end=564,
)
_sym_db.RegisterEnumDescriptor(_COMPONENT_SOURCETYPE)


_COMPONENT = _descriptor.Descriptor(
  name='Component',
  full_name='networkSpiceMessages.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='componentType', full_name='networkSpiceMessages.Component.componentType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='networkSpiceMessages.Component.nodes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='networkSpiceMessages.Component.values', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tolerance', full_name='networkSpiceMessages.Component.tolerance', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceType', full_name='networkSpiceMessages.Component.sourceType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPONENT_COMPONENTTYPE,
    _COMPONENT_SOURCETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=564,
)

_COMPONENT.fields_by_name['componentType'].enum_type = _COMPONENT_COMPONENTTYPE
_COMPONENT.fields_by_name['sourceType'].enum_type = _COMPONENT_SOURCETYPE
_COMPONENT_COMPONENTTYPE.containing_type = _COMPONENT
_COMPONENT_SOURCETYPE.containing_type = _COMPONENT
DESCRIPTOR.message_types_by_name['Component'] = _COMPONENT

Component = _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), dict(
  DESCRIPTOR = _COMPONENT,
  __module__ = 'component_pb2'
  # @@protoc_insertion_point(class_scope:networkSpiceMessages.Component)
  ))
_sym_db.RegisterMessage(Component)


# @@protoc_insertion_point(module_scope)
