# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulationrequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import component_pb2 as component__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulationrequest.proto',
  package='networkSpiceMessages',
  syntax='proto3',
  serialized_pb=_b('\n\x17simulationrequest.proto\x12\x14networkSpiceMessages\x1a\x0f\x63omponent.proto\"\x87\x02\n\x11SimulationRequest\x12\x33\n\ncomponents\x18\x01 \x03(\x0b\x32\x1f.networkSpiceMessages.Component\x12\r\n\x05nodes\x18\x02 \x03(\r\x12\x44\n\x04type\x18\x03 \x01(\x0e\x32\x36.networkSpiceMessages.SimulationRequest.SimulationType\x12\r\n\x05\x62\x65gin\x18\x04 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x01\x12\x0e\n\x06points\x18\x06 \x01(\x04\x12\x0c\n\x04step\x18\x07 \x01(\x01\".\n\x0eSimulationType\x12\r\n\tFrequency\x10\x00\x12\r\n\tTransient\x10\x01\x62\x06proto3')
  ,
  dependencies=[component__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIMULATIONREQUEST_SIMULATIONTYPE = _descriptor.EnumDescriptor(
  name='SimulationType',
  full_name='networkSpiceMessages.SimulationRequest.SimulationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Frequency', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Transient', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=284,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONREQUEST_SIMULATIONTYPE)


_SIMULATIONREQUEST = _descriptor.Descriptor(
  name='SimulationRequest',
  full_name='networkSpiceMessages.SimulationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='networkSpiceMessages.SimulationRequest.components', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='networkSpiceMessages.SimulationRequest.nodes', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='networkSpiceMessages.SimulationRequest.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='begin', full_name='networkSpiceMessages.SimulationRequest.begin', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='networkSpiceMessages.SimulationRequest.end', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='networkSpiceMessages.SimulationRequest.points', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='networkSpiceMessages.SimulationRequest.step', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIMULATIONREQUEST_SIMULATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=330,
)

_SIMULATIONREQUEST.fields_by_name['components'].message_type = component__pb2._COMPONENT
_SIMULATIONREQUEST.fields_by_name['type'].enum_type = _SIMULATIONREQUEST_SIMULATIONTYPE
_SIMULATIONREQUEST_SIMULATIONTYPE.containing_type = _SIMULATIONREQUEST
DESCRIPTOR.message_types_by_name['SimulationRequest'] = _SIMULATIONREQUEST

SimulationRequest = _reflection.GeneratedProtocolMessageType('SimulationRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONREQUEST,
  __module__ = 'simulationrequest_pb2'
  # @@protoc_insertion_point(class_scope:networkSpiceMessages.SimulationRequest)
  ))
_sym_db.RegisterMessage(SimulationRequest)


# @@protoc_insertion_point(module_scope)
